### ISSUE TITLE
Perserve gamma calibration

### ISSUE THREAD

**Issue by maandree** [dariost/XRainbow#2]
It would be nice if xrainbow and grainbow read the current gamma ramps and restored them upon exiting.

Since the gamma settings are change so rapidly I do not think it is necessary to apply the effect beneath the gamma corrections, but if you want to be pedantic you should do that too. Doing so is a bit of work, you would have to apply your effects and then the gamma corrections on top of that using intropolation (that is, create a function like y = calibration(rainbow(x)).)

**Comment by dariost** [comment]
Now XRainbow restores the original gamma ramps. GRainbow already did that.

For now I won't implement the second bit you're talking about because I don't see a major benefit for the purpose of this application.

**Comment by maandree** [comment]
Okay.

No, I won't implement the second part either, it is way overkill for this, and should actually be display server's resonsibility. I hope that they one day support concurrent gamma-filters.
